title: Jonathan Tonglet
logo: /img/profile_pic.jpg
description: Incoming Master of AI student at KULeuven. Passionated about applications at the intersection of NLP, economics and social sciences.
theme: jekyll-theme-minimal
