title: Jonathan Tonglet
logo: /img/profile_pic.jpg
description: Incoming Master of AI student at KULeuven.  Passionate about applications of Machine Learning and NLP in Economics and Social Sciences.
theme: jekyll-theme-minimal
